# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’
# Uncomment this line if you're using Swift
 use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!

target 'dcrdminer' do
  pod 'SwiftyJSON'
end

target 'dcrdminerTests' do
  pod 'SwiftyJSON'
end
